---
title: "R Notebook"
output: html_notebook
---

```{r}
library(shiny)
library(tidyverse)
library(ggplot2)
```

```{r}
birds_21 <- read_csv("clean_data/birds_cleaned_data.csv", lazy = F)
```

```{r}
birds <- c("Tropicbird" = "#50e2ea", "Tern" = "#4edae5", "Skua" = "#4bd2df", 
           "Sheathbill" = "#49cada", "Shearwater" = "#47c2d4", 
           "Shag" = "#45bbcf", "Seabird" = "#42b3c9", "Procellaria" = "#40abc4",
           "Prion" = "#3ea3be", "Petrel" = "#3b9bb9", "Penguin" = "#3993b3", 
           "Noddy" = "#378bae", "Mollymawk" = "#3483a8", "Jaeger" = "#327ba3", 
           "Gull" = "#30739d", "Gannet" = "#2e6c98", "Fulmar" = "#2b6492", 
           "Frigatebird" = "#295c8d", "Cormorant" = "#275487", 
           "Booby" = "#244c82", "Albatross" = "#22447c")
```



```{r}
bird_count <- birds_21 %>%
  filter(!is.na(bird_type)) %>%
  group_by(bird_type) %>%
  mutate(feeding = if_else(feeding %in% "YES", 1, 0),
         on_ship = if_else(on_ship %in% "YES", 1, 0),
         in_hand = if_else(in_hand %in% "YES", 1, 0),
         fly_by = if_else(fly_by %in% "YES", 1, 0)) %>%
  summarise(sighting_count = sum(total_sighting, na.rm = TRUE),
            feeding_count = sum(feeding, na.rm = TRUE),
            on_ship_count = sum(on_ship, na.rm = TRUE),
            in_hand_count = sum(in_hand, na.rm = TRUE),
            fly_by_count = sum(fly_by, na.rm = TRUE))
```


```{r}
make_bird_plot <- function(data, plot_input, log_scale = FALSE) {
  
  # calculate maximum limits based on the data
  max_count <- max(data[[plot_input]])
  
  # ... then make the plot
  p <- data %>% 
    ggplot() +
    aes(x = .data[[plot_input]],
        y = bird_type,
        fill = bird_type) +
  geom_col(colour = "black", show.legend = FALSE) +
  scale_fill_manual(values = birds)

  # if the chose log scale add in a log scale  
  if (log_scale) p <- p + scale_x_continuous(trans = "log10") + 
                           labs(y = "\n Bird Names",
                                x = "Number of Birds Seen \n Log10 scale")
  # otherwise do your manual scale option using the calculated value max_count
  else p <- p + scale_x_continuous(
    limits = c(0,max_count),
    breaks  = c(seq(0,max_count, (max_count)/5)) 
    ) +
    labs(y = "\n Bird Names",
       x = "Number of Birds Seen")
  
  return(p)
}
```

# Test Function

```{r}
# test inputs so they look like what shiny will give us for user inputs.
input <- list(
  bird_input = "sighting_count"
)


make_bird_plot(bird_count, input$bird_input, log_scale = T)
```



```{r}
variants <- birds_21 %>% 
              filter(bird_type == "Albatross") %>% 
              group_by(common_name) %>% 
              summarise(count = n())
```




```{r}
variants_plot <- function(data, plot_input, log_scale = FALSE) {
  
  # calculate maximum limits based on the data
  #max_count <- max(data[[plot_input]])
  
  
  
  
  
  # ... then make the plot
  p <- data %>% 
    filter(bird_type == plot_input) %>% 
              group_by(common_name) %>% 
              summarise(count = n()) %>% 
    ggplot() +
    aes(x = count,
        y = common_name,
        fill = common_name) +
  geom_col(colour = "black", show.legend = FALSE) +
  scale_fill_manual(values = birds)

  # if the chose log scale add in a log scale  
  if (log_scale) p <- p + scale_x_continuous(trans = "log10") + 
                           labs(y = "\n Bird Names",
                                x = "Number of Birds Seen \n Log10 scale")
  # otherwise do your manual scale option using the calculated value max_count
  else p <- p + 
    #   scale_x_continuous(
    # limits = c(0,max_count),
    # breaks  = c(seq(0,max_count, (max_count)/5)) 
    # ) +
    labs(y = "\n Bird Names",
       x = "Number of Birds Seen")
  
  return(p)
}
```


```{r}
# test inputs so they look like what shiny will give us for user inputs.
input <- list(
  variants_input = "Booby"
)


variants_plot(birds_21, input$variants_input, log_scale = T)
```


