---
title: "R Notebook"
output: html_notebook
---

```{r}
library(shiny)
library(tidyverse)
library(shinythemes)
library(stringi)
```

```{r}
seabirds_cleaned_data <- read_csv("data/seabirds_cleaned_data.csv")
```

```{r}

birds_9 <- seabirds_cleaned_data %>% 
  group_by(common_name) %>% 
  mutate(common_name = if_else(str_detect(common_name, 
                                          "(?i)shearwater"),"Shearwater", 
                               common_name),
         common_name = if_else(str_detect(common_name, 
                                          "(?i)albatross"), "Albatross",
                               common_name),
         common_name = if_else(str_detect(common_name, 
                                          "(?i)mollymawk"), "Mollymawk",
                               common_name),
         common_name = if_else(str_detect(common_name, 
                                          "(?i)petrel"), "Petrel",
                               common_name),
         common_name = if_else(str_detect(common_name, 
                                          "(?i)prion"), "Prion",
                               common_name),
         common_name = if_else(str_detect(common_name, 
                                          "(?i)skua"), "Skua",
                               common_name),
         common_name = if_else(str_detect(common_name, 
                                          "(?i)penguin"), "Penguin",
                               common_name),
         common_name = if_else(str_detect(common_name, 
                                          "(?i)Red-tailed tropicbird"), 
                               "Red-tailed tropicbird",
                               common_name),
         common_name = if_else(str_detect(common_name, 
                                          "(?i)Brown noddy"), "Brown noddy",
                               common_name)
  ) %>% 
  filter(common_name %in% c("Shearwater", "Albatross", 
                         "Mollymawk", "Petrel", 
                         "Prion", "Skua", 
                         "Penguin", "Brown noddy", 
                         "Red-tailed tropicbird"))
```

```{r}
sighting <-  birds_9 %>% 
            group_by(common_name) %>% 
            summarise(count = sum(total_sighting, na.rm = TRUE)) %>%
            mutate(sighting_id = row_number())

sighting %>% 
    ggplot() +
    aes(y = common_name, 
        x = count, fill = sighting_id) +
    geom_col(colour = "black") +
    theme(legend.position = "none") +
    scale_x_continuous(breaks = c(1, 5, 10, 1000, 6000, 1400000),
                       limits = c(1,1400000), 
                       trans = "log10") +
    labs(y = "\n Bird Names",
         x = "Number of Birds Seen \n Log10 scale")

# log10() as 1 or more birds are less than 10 and don't show on normal graph
```
1,394,468

```{r}
feeding <-  birds_9 %>% 
              group_by(common_name) %>% 
              filter(str_detect(feeding, "YES")) %>% 
              summarise(count = n()) %>% 
              mutate(feeding_id = row_number())

feeding %>% 
    ggplot() +
    aes(y = common_name, 
        x = count, fill = feeding_id) +
    geom_col(colour = "black") +
    theme(legend.position = "none") +
    scale_x_continuous(breaks = c(1, 5, 10, 100, 300, 800),
                       limits = c(1,800), 
                       trans = "log10") +
    labs(y = "\n Bird Names",
         x = "Number of Birds Seen Feeding \n Log10 scale")
# log10() as 1 or more birds are less than 10 and don't show on normal graph
```

```{r}
on_ship <-  birds_9 %>% 
              group_by(common_name) %>% 
              filter(str_detect(on_ship, "YES")) %>% 
              summarise(count = n()) %>% 
              mutate(on_ship_id = row_number())

on_ship %>% 
    ggplot() +
    aes(y = common_name, 
        x = count, fill = on_ship_id) +
    geom_col(colour = "black") +
    theme(legend.position = "none") +
    labs(y = "\n Bird Names",
         x = "Number of Birds Seen On Ship")
```


```{r}
in_hand <-  birds_9 %>% 
              group_by(common_name) %>% 
              filter(str_detect(in_hand, "YES")) %>% 
              summarise(count = n()) %>% 
              mutate(in_hand_id = row_number()) 

in_hand %>% 
    ggplot() +
    aes(y = common_name, 
        x = count, fill = in_hand_id) +
    geom_col(colour = "black") +
    theme(legend.position = "none") +
    labs(y = "\n Bird Names",
         x = "Number of Birds Seen In Hand")
```


```{r}
fly_by <-  birds_9 %>% 
              group_by(common_name) %>% 
              filter(str_detect(fly_by, "YES")) %>% 
              summarise(count = n()) %>% 
              mutate(fly_by_id = row_number())

fly_by %>% 
    ggplot() +
    aes(y = common_name, 
        x = count, fill = fly_by_id) +
    geom_col(colour = "black") +
    theme(legend.position = "none") +
    scale_x_continuous(breaks = c(1, 5, 10, 1000, 6000), 
                       limits = c(1,6000), 
                       trans = "log10") +
    labs(y = "\n Bird Names",
         x = "Number of Birds Seen Flying BY\n Log10 scale")
# log10() as 1 or more birds are less than 10 and don't show on normal graph
```



```{r}
library(shiny)
library(tidyverse)
library(shinythemes)


seabirds_cleaned_data <- read_csv("data/seabirds_cleaned_data.csv")
```

```{r}
birds_9 <- seabirds_cleaned_data %>% 
  group_by(common_name) %>% 
  mutate(common_name = if_else(str_detect(common_name, 
                                          "(?i)shearwater"),"Shearwater", 
                               common_name),
         common_name = if_else(str_detect(common_name, 
                                          "(?i)albatross"), "Albatross",
                               common_name),
         common_name = if_else(str_detect(common_name, 
                                          "(?i)mollymawk"), "Mollymawk",
                               common_name),
         common_name = if_else(str_detect(common_name, 
                                          "(?i)petrel"), "Petrel",
                               common_name),
         common_name = if_else(str_detect(common_name, 
                                          "(?i)prion"), "Prion",
                               common_name),
         common_name = if_else(str_detect(common_name, 
                                          "(?i)skua"), "Skua",
                               common_name),
         common_name = if_else(str_detect(common_name, 
                                          "(?i)penguin"), "Penguin",
                               common_name),
         common_name = if_else(str_detect(common_name, 
                                          "(?i)Red-tailed tropicbird"), 
                               "Red-tailed tropicbird",
                               common_name),
         common_name = if_else(str_detect(common_name, 
                                          "(?i)Brown noddy"), "Brown noddy",
                               common_name)
  ) %>% 
  filter(common_name %in% c("Shearwater", "Albatross", 
                            "Mollymawk", "Petrel", 
                            "Prion", "Skua", 
                            "Penguin", "Brown noddy", 
                            "Red-tailed tropicbird"))
```


```{r}
pal <- c("Shearwater" = "grey", "Albatross" = "blue", 
         "Mollymawk" = "yellow", "Petrel" = "green", 
         "Prion" = "pink", "Skua" = "purple", 
         "Penguin" = "orange", "Brown noddy" = "brown", 
         "Red-tailed tropicbird" = "red")
```

```{r}
names(birds_9)
head(birds_9)
```


```{r}

birds_9 %>% 
  group_by(common_name) %>% 
  mutate(feeding = if_else(feeding %in% "YES", 1, 0),
         on_ship = if_else(on_ship %in% "YES", 1, 0),
         in_hand = if_else(in_hand %in% "YES", 1, 0),
         fly_by = if_else(fly_by %in% "YES", 1, 0)) %>% 
  summarise(sighting_count = sum(total_sighting, na.rm = TRUE),
            feeding_count = sum(feeding, na.rm = TRUE),
            on_ship_count = sum(on_ship, na.rm = TRUE),
            in_hand_count = sum(in_hand, na.rm = TRUE),
            fly_by_count = sum(fly_by, na.rm = TRUE)) 
```


```{r}
library(leaflet)
```

```{r}

  leaflet(data = birds_9) %>%
  addTiles() %>%  # Add default OpenStreetMap map tiles
  addMarkers(label = birds_9$common_name, clusterOptions = markerClusterOptions()) 
  
 # Print the map
```


-45.91667
165.4000